Log errors when trying to access improper OME metadata (#36)
# References and relevant issues

Originally reported by @jamesyan-git 
When trying to load `RBC_tiny.czi` from
https://zenodo.org/records/7117784, there popped a pydantic error,
namely:
```
ValidationError: 1 validation error for Channel
acquisition_mode
  Input should be 'WideField', 'LaserScanningConfocalMicroscopy', 'SpinningDiskConfocal', 'SlitScanConfocal', 'MultiPhotonMicroscopy', 'StructuredIllumination', 'SingleMoleculeImaging', 'TotalInternalReflection', 'FluorescenceLifetime', 'SpectralImaging', 'FluorescenceCorrelationSpectroscopy', 'NearFieldScanningOpticalMicroscopy', 'SecondHarmonicGenerationImaging', 'PALM', 'STORM', 'STED', 'TIRF', 'FSM', 'LCM', 'Other', 'BrightField', 'SweptFieldConfocal' or 'SPIM' [type=enum, input_value='LatticeLightsheet', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/enum
```
This occurs because LatticeLightsheet is not a valid acquisition mode in
the above Enum (and this is defined, I think, by the OME schema)

[gist of full
traceback](https://gist.github.com/jamesyan-git/dfe194062171b42e9209d248487aa4e8)

# Description

This adds logging for such types of errors. The error occurs because
`ome_metadata` is attempted to be attached to the metadata of the image
when added to napari. Unlike the upstream `bioio` library, where you
would then say "ah, guess I can't use the ome_metadata", this library
needs to gracefully ignore the ome metadata, but I chose to log the
error. This error now would display as follows:
```
ConverterWarning: Failed to convert value for `Channel.acquisition_mode`
  `LatticeLightsheet` is not a valid `Channel_AcquisitionMode`!
23:22:15 : WARNING : MainThread : Could not parse OME metadata: 1 validation error for Channel
acquisition_mode
  Input should be 'WideField', 'LaserScanningConfocalMicroscopy', 'SpinningDiskConfocal', 'SlitScanConfocal', 'MultiPhotonMicroscopy', 'StructuredIllumination', 'SingleMoleculeImaging', 'TotalInternalReflection', 'FluorescenceLifetime', 'SpectralImaging', 'FluorescenceCorrelationSpectroscopy', 'NearFieldScanningOpticalMicroscopy', 'SecondHarmonicGenerationImaging', 'PALM', 'STORM', 'STED', 'TIRF', 'FSM', 'LCM', 'Other', 'BrightField', 'SweptFieldConfocal' or 'SPIM' [type=enum, input_value='LatticeLightsheet', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/enum. Raw metadata is still available in 'raw_image_metadata'.
```
I'm happy about this because its still quite informative, and lets folks
know that raw_image_metadata is available.

I assume this is quite the edge case, but if not, I can instead decrease
the log level.